# Usa la imagen oficial de Node.js
FROM node:20

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto del servidor de desarrollo de Angular
EXPOSE 4200

# Comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "start"]




